pingwit.server:
  name: "Egor Egorych"
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: pingwittest@gmail.com
    password: pingwittest2022
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

pingwit.email.property:
  from: "pingwittest@gmail.com"
  signature: "\n\n Best regards, \nPingwit."
  age: 17
