pingwit.server:
  name: "Egor Egorych"
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pingwit-java-1-1
    username: postgres
    password: docker
  jpa:
    show-sql: true
  liquibase:
    change-log: "classpath:db/changelog/changelog.xml"
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: pingwittest@gmail.com
    password: pingwittest2022
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

pingwit.email.property:
  from: "pingwittest@gmail.com"
  signature: "\n\n Best regards, \nPingwit."
  age: 17
